# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LOCK_xdc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_press_0_0/design_1_press_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_press_0_0 || ORIG_REF_NAME==design_1_press_0_0}]

# IP: bd/design_1/ip/design_1_press_1_0/design_1_press_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_press_1_0 || ORIG_REF_NAME==design_1_press_1_0}]

# IP: bd/design_1/ip/design_1_press_2_0/design_1_press_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_press_2_0 || ORIG_REF_NAME==design_1_press_2_0}]

# IP: bd/design_1/ip/design_1_press_3_0/design_1_press_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_press_3_0 || ORIG_REF_NAME==design_1_press_3_0}]

# IP: bd/design_1/ip/design_1_light_0_0/design_1_light_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_light_0_0 || ORIG_REF_NAME==design_1_light_0_0}]

# IP: bd/design_1/ip/design_1_clk_0_0/design_1_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_0_0 || ORIG_REF_NAME==design_1_clk_0_0}]

# IP: bd/design_1/ip/design_1_set_check_0_0/design_1_set_check_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_set_check_0_0 || ORIG_REF_NAME==design_1_set_check_0_0}]

# IP: bd/design_1/ip/design_1_check_0_1/design_1_check_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_check_0_1 || ORIG_REF_NAME==design_1_check_0_1}]

# IP: bd/design_1/ip/design_1_translate_0_1/design_1_translate_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_translate_0_1 || ORIG_REF_NAME==design_1_translate_0_1}]

# IP: bd/design_1/ip/design_1_translate_1_1/design_1_translate_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_translate_1_1 || ORIG_REF_NAME==design_1_translate_1_1}]

# IP: bd/design_1/ip/design_1_timeless_0_0/design_1_timeless_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_timeless_0_0 || ORIG_REF_NAME==design_1_timeless_0_0}]

# IP: bd/design_1/ip/design_1_add_0_2/design_1_add_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_add_0_2 || ORIG_REF_NAME==design_1_add_0_2}]

# IP: bd/design_1/ip/design_1_reset_0_2/design_1_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reset_0_2 || ORIG_REF_NAME==design_1_reset_0_2}]

# IP: bd/design_1/ip/design_1_rejudge_0_0/design_1_rejudge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rejudge_0_0 || ORIG_REF_NAME==design_1_rejudge_0_0}]

# IP: bd/design_1/ip/design_1_rset_0_0/design_1_rset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rset_0_0 || ORIG_REF_NAME==design_1_rset_0_0}]

# IP: bd/design_1/ip/design_1_creat_0_0/design_1_creat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_creat_0_0 || ORIG_REF_NAME==design_1_creat_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
